.POSIX:

all:

install:
	mkdir -p $(DESTDIR)/usr/share/gconf/schemas
	cp -f location.schemas $(DESTDIR)/usr/share/gconf/schemas/

uninstall:
	rm -f $(DESTDIR)/usr/share/gconf/schemas/location.schemas

clean:
